
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'BF4338C6BD2D39374DFF687F40C72265'
    
_lr_action_items = {'RCURLY':([6,10,],[8,11,]),'LCURLY':([3,7,],[4,9,]),'PLUS':([4,9,],[6,10,]),'EXTENDS':([3,],[5,]),'IDENTIFIER':([2,5,],[3,7,]),'CLASS':([0,],[2,]),'$end':([1,8,11,],[0,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'classdecl':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> classdecl","S'",1,None,None,None),
  ('classdecl -> CLASS IDENTIFIER LCURLY PLUS RCURLY','classdecl',5,'p_classdecl','decafparser.py',25),
  ('classdecl -> CLASS IDENTIFIER EXTENDS IDENTIFIER LCURLY PLUS RCURLY','classdecl',7,'p_classdecl','decafparser.py',26),
]
